--Average Population of Each Continen
SET NOCOUNT ON;

SELECT COUNTRY.CONTINENT ,CEILING(AVG(CITY.POPULATION)) 
 FROM CITY
INNER JOIN COUNTRY
ON COUNTRY.CODE=CITY.COUNTRYCODE
GROUP BY COUNTRY.CONTINENT
go