--The PADS
SET NOCOUNT ON;

SELECT NAME + '(' + LEFT(OCCUPATION,1) + ')' FROM OCCUPATIONS
ORDER BY NAME
SELECT 
    'There are a total of ' + CAST(COUNT(*) AS VARCHAR(10)) + ' ' + LOWER(Occupation) + 's.'
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(*), OCCUPATION;



go